
all:
	g++ -std=c++17 -O3 -DSCDEKKERS  main.cpp -lpthread -o scdekker
	g++ -std=c++17 -O3 -DRDEKKERS   main.cpp -lpthread -o rdekkers
	g++ -std=c++17 -O3 -DTSODEKKERS main.cpp -lpthread -o tsodekkers
